spring:
  application:
    name: SpringBootREST3
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 9100

management:
  endpoints:
    web:
      exposure:
        include: ["health","prometheus","metrics","info"]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    java:
      enabled: true
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces


application:
  spring:
    endpoints:
      exclude: /v3/rest/hello, /v3/rest/helloPost, /error, /v3/restClient/helloPostClient, /v3/rest/home, /actuator/**, /v3/rest/getMoviesByDirectorAndGenre/**, /v3/rest/authenticate, /v3/api-docs, /v3/api-docs.yaml, /v3/rest/addMovie, /v3/rest/getOrder3/**

opentracing:
  jaeger:
    enabled: true

jwt:
  expirationInMillis: 180000
  secret: abcdefghijklmnopqrstuvwxyz
  refreshTokenExpirationInMillis: 180000