spring:
  application:
    name: SpringBootREST3

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 9100

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info

application:
  spring:
    endpoints:
      exclude: /v3/rest/hello, /v3/rest/helloPost, /v3/rest/home, /actuator/**
